import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const josefinSans = Josefin_Sans({
    weight:["400","700"],
    subsets:["latin","vietnamese"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.className} antialiased w-screen overflow-x-hidden text-black bg-white`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
